# tmux
if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
	if [[ $TERM_PROGRAM == vscode ]]; then
		tmux new 2> /dev/null
	else
		tmux attach 2> /dev/null || cd ~ || tmux new 2> /dev/null
	fi
fi
